### PR TITLE
feat(SelectWidget): react component for select input

### PR DESCRIPTION
**Pull request by aronhelser**
@jourdain is it OK to label this a feature? It's a new, simple widget.

Fixes for TextInputWidget and ContentEditableWidget as well.

### CODE REVIEW

**Comment by aronhelser** [comment]
Hmm, it's not displaying the 'fa-check' icon in the examples. Undecorated classname, I guess? I'm not sure why this works elsewhere and not here.

**Comment by jourdain** [comment]
I'm not sure to see what that Select Widget is bringing in. It seems like a stateless component.
Also no style is provided with it. Or we can not provide one from the outside.

Might be more interesting to come up with a stateless version that use a data model like below (or else) as well as a stateful version using the stateless:

{ 
  selected: [ 'a', 'b'],
  values: [
   { label: 'A', value: 'a' },
   { label: 'B', value: 'b' },
   { label: 'C', value: 'c' },
  ]
}

**Comment by jourdain** [comment]
fa-check does not exist it has been mangled by module-css. You get that string from the style object that you import.

**Comment by aronhelser** [comment]
SelectWidget is motivated by the data-cleaner UI. I needed a selector that could display outside the parent container (a table cell). I can make it stateless and add props for classnames so it can be externally styled. I should be able to put together an stateful example, too.

Is it OK as a 'feat()' ?

 I figured out fa-check - I was using InlineToggleButtonWidget as an example, and it requires the fa CSS at the top of the example code.

**Comment by jourdain** [comment]
This seems tiny, I would rather do a fix.

**Comment by TristanWright** [comment]
This widget seems very similar to the already existing [React/Properties/Enum](https://github.com/Kitware/paraviewweb/blob/master/src/React/Properties/EnumProperty/index.js)?

It already supports `<select multiple>` and you could add a prop to that which removes the label header if you just want a select element.

**Comment by aronhelser** [comment]
Good suggestion. I missed that when I searched for <select>. I've added an example, and I've got it working without a header/help by making those props conditional. I'll push soon.

I have some styling issues - too much custom padding for the Properties panel. But it works fine.

**Comment by aronhelser** [comment]
Updated with styling fixes and new example for EnumProperty. OK with you?

**Comment by TristanWright** [comment]
It looks good. 
The _enum-property solo_ is a bit wider than the others, could be fixed with 

```css
.soloContainer {
  composes: container from './CellProperty.mcss'; /* no change */
  width: calc(100% - 20px); /* as other enums have, right now it's just 100% */
  /* padding: 2px; remove this attribute, CellProperty_container already has 8px 10px as its values*/
}
```

screen shot 2016-11-28 at 11 01 56

**Comment by aronhelser** [comment]
This is on purpose - if you are using it without the header/help that makes
it part of the Properties group, I want it to take up 100% of whatever
container it's in. Looks a bit weird in the example, though, doesn't it?

**Comment by TristanWright** [comment]
Still looks good then, however the `<select>` matches the parent's `max-width: 300px`, but its container's padding pushes it outside of the parent's max-width rule.

screen shot 2016-11-28 at 11 18 48

**Comment by aronhelser** [comment]
OK, missed that with box-model: border-box set in ERS app. Updated container style to 
`width: calc(100% - 4px)` to take care of that, and adding a chore(dist) commit.

**Comment by TristanWright** [comment]
lgtm 👍

**Pull request merged**
