### PR TITLE
fix(VtkRenderer): Properly push props at initialization time

### PR DESCRIPTION
**Pull request by jourdain**

### CODE REVIEW

**Comment by felixveysseyre** [comment]
@jourdain It should work but the implementation is not optimal.

React method `componentWillReceiveProps` will always return the complete set of properties. For each property, you need to check if the new value is different than the current one:
```
componentWillReceiveProps(nextProps) {
	if (nextProps.myProp !== this.props.myProp)
	{
		//Do something
	}
}
```

**Comment by jourdain** [comment]
You really have hard time with code responsibility leakage. This is already managed in each component individually. Therefore, it is not needed to duplicated that check again and again in various layer of your application.

**Comment by felixveysseyre** [comment]
These check are really required here.

As I explained in my previous message, you will always receive a complete set of properties (containing both changed and unchanged props) in componentWillReceiceProps method. Therefore, with your implementation, you will send to the server several useless orders, as you will ask to update some parameters which already have the value you asked for.

**Comment by jourdain** [comment]
No they are not! And if they are, the issue is somewhere else...

Can you point me the code that send those useless information when they are the same? Because that would be their responsibility to handle that use case, not the application.

**Comment by jourdain** [comment]
BTW, I'm well aware that method get called each time any property change with all the properties.

**Comment by jourdain** [comment]
Better design here: https://github.com/Kitware/paraviewweb/pull/446

**Comment by jourdain** [comment]
I was taking the time to explain so you can learn and get better at your development/design. But I guess you could not grasp what I was talking about.

**Pull request closed without merging**
