### PR TITLE
fix(VTKRenderer): Fix VTKRenderer initial values setting

### PR DESCRIPTION
**Pull request by felixveysseyre**
Following earlier discussion with @jourdain

### CODE REVIEW

**Comment by jourdain** [comment]
This is a react component and therefore should follow their mantra using properties. My suggestion was just to add 1 line.

**Comment by felixveysseyre** [comment]
This is the cleanest way to implement such features.
Having custom dedicated update methods will allow to reuse these features and therefore allow the Component to scale in complexity.

**Comment by jourdain** [comment]
I don't agree with scalability regarding `new feature = new method`. To me that is the definition of not scaling.

**Comment by felixveysseyre** [comment]
I feel like it's a good thing to have these update methods around, as it allow us to update each parameter distinctly.
And moreover, having the possibility to access these update mechanisms from the parent component can always be useful.

But sure, it's taking more lines than the other method we discuss about.

**Comment by jourdain** [comment]
By splitting them you are making the code more error prone for user since they need to happen in two location (At initialization and when the properties change). Having a single method `pushSettingsToServer()` make things slightly more simple and less error prone. Moreover, the implementation of that method could allow you to only update a subset of those server props if not present in the settings = {}.
On top of that without any of the methods you added, you could already set/push those things individually if you really wanted to (without any code change) from the parent component.

**Comment by jourdain** [comment]
Can you validate https://github.com/Kitware/paraviewweb/pull/444 to make sure I don't have any typo.

**Pull request closed without merging**
