### PR TITLE
Ignore vim swap files

### PR DESCRIPTION
**Pull request by ronichoudhury**

### CODE REVIEW

**Comment by jourdain** [comment]
can you push your branch to Kitware/paraviewweb so Travis could validate it for you?

**Comment by ronichoudhury** [comment]
Ah, I think yesterday I didn't have push access. Looks like everything is green now!

**Comment by jourdain** [comment]
Yes I added your team yesterday.

**Comment by ronichoudhury** [comment]
Thanks Seb.

**Comment by jourdain** [comment]
You are welcome... BTW, if you think that Candela can be a submodule of ParaViewWeb, then fill free to add it so it could simplify the commercial talk around our brands and code base.

**Comment by ronichoudhury** [comment]
Cool, that's something to think about. I will discuss with you and Jeff.

**Pull request merged**
