### PR TITLE
Update pvw build system

### PR DESCRIPTION
**Pull request by scottwittenburg**
This updates to the latest `kw-web-suite`, but ignores some new style rules which generate too many issues to fix at the moment.  Also updates to `react-dom:16.4.2`  to fix a vulnerability.

### CODE REVIEW

**Comment by scottwittenburg** [comment]
@jourdain updating to `kw-web-suite:8.0.0` resulted in over 2K new lint errors and running eslint with `--fix` said it was only going to be able to fix 71 of them.  I started fixing them manually, but then reverted and just disabled some of the rules, because it seems like it will take a decade.

But let me know if some of those rules I disabled should actually be addressed.

**Comment by jourdain** [comment]
disabling rules for now is good.

**Comment by scottwittenburg** [comment]
Since everything's green, we could merge, unless you see anything you want changed.

**Pull request merged**
