### PR TITLE
fix(LinearPieceWiseEditor): Add a way to externally set the points in…

### PR DESCRIPTION
**Pull request by mathturtle**
… the LinearPieceWiseEditor

@jourdain

### CODE REVIEW

**Comment by jourdain** [comment]
LGTM.

You may want to also fix an interaction bug. You can reproduce it by trying to delete the point before last.

**Comment by mathturtle** [comment]
Delete the point before last?  How do you delete points?

**Comment by jourdain** [comment]
How do you create point?

**Comment by jourdain** [comment]
```js
   this.onClick = (event) => {
      // Remove point
      if (event.metaKey || event.ctrlKey) {
        const click = getNormalizePosition(event, this.ctx, this.radius);
        const controlPoint = findPoint(click, this.controlPoints);
        if (controlPoint && !controlPoint.fixedX) {
          this.controlPoints.splice(controlPoint.index, 1);
        }
        this.render();
      }
    };

    this.onDblClick = (event) => {
      const point = getNormalizePosition(event, this.ctx, this.radius);
      this.controlPoints.push(point);
      sortPoints(this.controlPoints);
      this.render();
    };
```

**Comment by mathturtle** [comment]
Deleting the point before last worked fine here.  Is this an OSX bug?

**Comment by jourdain** [comment]
I do not remember for sure the issue or how to reproduce it. 
So try to see if you can make it break in someway by creating points, moving them around and delete them.

**Comment by mathturtle** [comment]
That's what I've been doing.  The only thing that I've found so far is that if you click in just the right spot you can create a point with an x coordinate of 1.01 or -0.01, which breaks the range of [0,1] assumption.

**Comment by mathturtle** [comment]
Oh, and if you are dragging a point around and the mouse leaves the widget it loses track of the fact that you were interacting even if the mouse re enters the widget later without having released the button.

**Comment by jourdain** [comment]
cool, I'm just thinking it is a good time to make that component more robust as it was made in a hurry.

**Comment by mathturtle** [comment]
Updated to fix the clamping problem.  I'm not quite sure how to fix the other one.

**Comment by mathturtle** [comment]
Looking at the javascript mouse event documentation I'm not sure that the leaving and reentering the widget problem can be solved at all.  But I haven't found any other issues.

**Comment by mathturtle** [comment]
I found it.  Just an internal indexing of the controlPoints list that wasn't getting updated after a delete.

**Comment by jourdain** [comment]
awesome... Thanks...

**Pull request merged**
