### PR TITLE
fix(SelectionEditorWidget): Remove dependency on providers and make i…

### PR DESCRIPTION
**Pull request by jourdain**
…t stateless

### CODE REVIEW

**Comment by jourdain** [comment]
@aronhelser: Still need to fix the fact that it is pushing the selection even if I'm not changing it by just triggering an onBlur(). Otherwise it look great...

**Comment by aronhelser** [comment]
OK, I read it three times, and I think I get it. When it's instantiated, we can pass in an 'onChange' function callback that uses the provider to propagate the selection. You also decided to not update the generation number when the changes are local. It makes sense to me. I wouldn't change the name to SelectionEditorWidgetReact - why would you make the internal name different from the directory name?Looks good to me!

Random idea - you could JSON.stringify() the annotation and do a string compare to see if it changed.

**Comment by jourdain** [comment]
I did not change the name, I think I picked the name you gave to the react class.
Then it is just that functions should not start with an Upper case letter.
I will do another pass for the style and remove the eslint-disable.

Agree with the JSON.stringify(), that was my plan, but I wanted to go home. ;-)

**Comment by jourdain** [comment]
We can talk more about it if you want tomorrow...

**Pull request merged**
