### PR TITLE
fix(IO): Allow simulation steps to be passed

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by cjh1** [comment]
@TristanWright PTAL

**Comment by TristanWright** [comment]
LGTM

**Comment by cjh1** [comment]
@TristanWright This change seems to have been lost when we moved this code to HPCCloud? Not sure where editSimulation ended up?

**Comment by TristanWright** [comment]
whoa, I must've been carrying it over right as you made this change.
`editSimulation` is in `src/network/simulations`

**Comment by TristanWright** [comment]
addressed in [hpccloud/pulls/416](https://github.com/Kitware/HPCCloud/pull/416)

**Pull request merged**
