### PR TITLE
Fix mouse pan jump issue

### PR DESCRIPTION
**Pull request by ronichoudhury**

### CODE REVIEW

**Comment by jourdain** [comment]
Thanks Roni for taking care of it... Does that mean you are using it?

**Comment by jourdain** [comment]
I had to push your branch to that repo in order to trigger a test build.

**Comment by ronichoudhury** [comment]
I am not using it specifically, but I thought I would try to get involved (at least a little bit) with development :)

My comitizen message was ok? Do you require all commits to have a "scope"?

**Comment by jourdain** [comment]
Yes that helps => see what was generated

https://github.com/Kitware/paraviewweb/releases/tag/v1.2.29

And the result of your work

http://kitware.github.io/paraviewweb/examples/ImageRenderer/

**Comment by ronichoudhury** [comment]
Oh that's neat. I didn't realize the release process was automatic via
comitizen as well. I was vaguely wondering how you guys were cutting so
many releases ;)

**Comment by jourdain** [comment]
Yes, as easy as pushing commits... 
That's easy as that with an automatic update of the web site as well (examples, API, ...).

**Pull request merged**
