### PR TITLE
Native feel tweaks

### PR DESCRIPTION
**Pull request by aronhelser**
@scottwittenburg @vibraphone A few of the comments from the meeting.

### CODE REVIEW

**Comment by aronhelser** [comment]
Looking at the headers again, now "Only Selected (19)" doesn't read correctly when the box isn't checked. Where should we put the active field count, or maybe take it out since the workbench/portal will display it in a central place?

**Comment by scottwittenburg** [comment]
I don't recall having a place carved out for that in the portal/workbench, but I'm not sure how important that piece of information is.  What do you think about just removing it from the field selector for now?  If someone asks for it, we can put it somewhere else.

**Comment by aronhelser** [comment]
ERS specifically requested a field count based on one user's feedback - it was a while back. I adjusted it for FieldSelector, and removed from the HistogramSelector. OK to merge?

**Comment by patrickoleary** [comment]
I remember.

**Comment by jourdain** [comment]
sure go for it

**Pull request merged**
