### PR TITLE
fix(LinearPieceWiseEditor): Add support for having an active point

### PR DESCRIPTION
**Pull request by mathturtle**
@jourdain How is this?

### CODE REVIEW

**Comment by jourdain** [comment]
It is a good start, but I think you should have option/API to enable/disable a control point.
Moreover, the point you just move should not lose its "active" state (maybe).

As you may use side control to fine position it after a mouse positioning. 

What do you think?

**Comment by mathturtle** [comment]
> but I think you should have option/API to enable/disable a control point

Do you mean set which point is active and clear the active point?

> the point you just move should not lose its "active" state

It shouldn't.  That was one of the things I tested.  The only things that should clear it are clicking on the empty background and deleting the currently active point.

**Comment by jourdain** [comment]
Ok maybe by looking at the code I missed that part

**Comment by mathturtle** [comment]
Updated to add API to set/clear the active point.

**Pull request merged**
