### PR TITLE
fix(HistogramSelector): Scoring - uncertainty regions shouldn't overlap

### PR DESCRIPTION
**Pull request by aronhelser**
While dragging and when committing to values in the divider popup, make the
uncertainty of the edited divider not overlap with neighbors. When the divider's
value is changed or it's dragged, if it ends up inside another divider's
uncertain region, shrink the other divider's uncertainty.

Also represent uncertainty internally as [0,1] instead of [0,100%]
to make communication with the server easier.

### CODE REVIEW

**Comment by aronhelser** [comment]
@scottwittenburg this one is a bit simpler, but you might want to try it out...

**Comment by scottwittenburg** [comment]
LGTM.  I tried it out, and seems like it does what we talked about.  

One thing:  when you use the input widget to adjust uncertainty, it allows the regions to overlap until the dialog goes away, at which point the uncertainty is reduced.  On the other hand, you have instantaneous feedback when dragging the divider with associated uncertainty towards another divider with uncertainty.

I'm ok with it, just pointing out something I noticed.

**Comment by aronhelser** [comment]
Yes, that's a consequence of how the input field events are processed. They separate into 'input' and 'change' events. I didn't want to validate on 'input' events, because you can type a number, and if you mis-type or something, I'd have to erase what you had typed and replace it. 

Hmm, what if I clamped what I displayed, but didn't update what was in the input field? Would it be strange to type '20000' and have the uncertainty rect not change at all as you typed those extra zeros?

**Comment by scottwittenburg** [comment]
I agree that it's very disconcerting (to put it nicely) when I'm typing in a field and the field makes its own changes as I type.

Your clamping idea seems reasonable, but you're right that it may be strange to have it sometimes seemingly ignore what you type.

I think what you have now could be good enough.  Any thoughts @jourdain?

**Comment by jourdain** [comment]
what you have now seems good enough

**Comment by aronhelser** [comment]
I couldn't resist :) I added a 'blur' handler, and I found another case where the changing the divider's value in the popup needed to update the popup's uncertainty number. I'm done now!

**Pull request merged**
