### PR TITLE
fix(NumberSliderWidget): Update style so that input box will not wrap…

### PR DESCRIPTION
**Pull request by mathturtle**
… to next line

### CODE REVIEW

**Comment by mathturtle** [comment]
@jourdain

**Comment by jourdain** [comment]
Are you sure it does not wrap now on all the browser?

**Comment by jourdain** [comment]
You need to push your branch to the repo so travis can test it.

**Comment by mathturtle** [comment]
> Are you sure it does not wrap now on all the browser?

No.  I made the changes based on what we did to DoubleSliderWidget (tested on the demo page with firebug).  I'm not actually sure how to test paraviewweb's tests locally.  Also, which browsers should I be testing with?

> You need to push your branch to the repo so travis can test it.

OK, I didn't know that.  I'll push it there and open and new PR after I've tested it on more browsers.

**Comment by jourdain** [comment]
ok, for the browsers: Chrome, Firefox, Safari

**Comment by TristanWright** [comment]
@mathturtle In what browser(s) were you seeing this issue that prompted the PR?

**Comment by mathturtle** [comment]
Firefox (45.0.1) on Ubuntu 15.10.  I made a similar fix for DoubleSliderWidget when I first started working on lightviz.  See this commit in tonic-ui: https://github.com/Kitware/tonic-ui/commit/5c6502bfad9c62cc47c89eb6a94f1f1a2c41c3ce

Here is a screenshot showing what I am seeing.
sliderwidgetbug

**Comment by mathturtle** [comment]
I tested on OSX and couldn't reproduce it.  Must be a linux thing?

**Comment by TristanWright** [comment]
Yeah a combination of native system controls and DOM rendering discrepancies. Makes me wonder what issues might appear on Windows? ... maybe another time :) 

I tried out this branch on OSX across the three browsers, looked good to me.

**Comment by mathturtle** [comment]
@TristanWright How do you test a paraviewweb branch?  My knowledge of how to build an application against a modified local upstream is obsolete since we don't use tonic anymore.  I've been testing by modifying the CSS of the example page in Firebug.

**Comment by TristanWright** [comment]
With the branch checked out.
```sh
npm run http:www #this will take a while, it's building the all the docs and examples.
```

In a browser go to `localhost:4000/paraviewweb/examples/NumberSliderWidget/` and you'll be able to view the widget's example. If/when you make changes, instead of rebuilding all the examples and restarting the server, in a separate terminal run:

```sh
npm run bin:pvw-doc -- -e NumberSliderWidget
# -l lists examples if you're wondering the exact name of the example to build.
```

Refresh the example page to view any changes. Hope this helps.

--

I thought these would already be written down somewhere but these instructions would be good to add to [`CONTRIBUTING.md`](https://github.com/Kitware/paraviewweb/blob/master/CONTRIBUTING.md) or [`DEVELOPMENT.md`](https://github.com/Kitware/paraviewweb/blob/master/DEVELOPMENT.md)

**Comment by mathturtle** [comment]
Thanks @TristanWright.

> `npm run http:www`
I get the following error when I run this:
```
shawn@rukbat:~/dev/paraviewweb$ npm run http:www
npm ERR! Linux 4.2.0-35-generic
npm ERR! argv "/home/shawn/tools/node/bin/node" "/home/shawn/tools/node/bin/npm" "run" "http:www"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12

npm ERR! missing script: http:www
npm ERR! 
```
The other command to rebuild the NumberSliderWidget example worked, so why do you think this one failed?  Am I missing a dependency?


> I thought these would already be written down somewhere but these instructions would be good to add to CONTRIBUTING.md or DEVELOPMENT.md

I looked earlier but couldn't find it.  When I figure it out I'll add a documentation commit to this branch that updates it with instructions.

**Comment by jourdain** [comment]
```sh
$ npm run doc:http
```

**Comment by TristanWright** [comment]
yes `npm run doc:http` sorry, was thinking of the older scripts >_<

**Comment by mathturtle** [comment]
I've tested this on Windows with Firefox and IE and tested locally on Linux with Firefox and Chromium.  I'm going to make a new PR with the rebased branch and add a documentation commit to explain how to test changes.

**Pull request closed without merging**
