### PR TITLE
fix(NativeImageRenderer): Redraw image when size change triggered

### PR DESCRIPTION
**Pull request by mathturtle**
When a size change is triggered, redraw the image.  This change fixes the issue in LightViz where
the VtkRenderer goes blank when the colormap editor's LinearPieceWiseEditor is shown for the first
time.  The second canvas' creation was causing the first one to blank, and this makes it repaint
properly.

@jourdain This fixes LightViz, but it may not be the right fix.  I'm not sure what the right fix for this is, but I have identified the problem.  If this isn't the right fix for it, can you let me know what is?

### CODE REVIEW

**Comment by mathturtle** [comment]
@jourdain ping?

**Comment by mathturtle** [comment]
So it turns out that this fixed one problem to cause another.  Now when you initially load the page there is an error on the console.  Everything else seems to work, but I can't figure out how to get this error message to go away.

**Comment by jourdain** [comment]
Yes I was scared for the very first time when no image was available. But I assumed you tested it before.

You might be able to guard that call only if (image.src && image.loaded). (Need to double check the second condition as I can't remember which is the proper flag to check.

**Comment by mathturtle** [comment]
I tested if it worked... I guess I didn't have the console open.  Based on 5 minutes of searching, the flag doesn't exist.  The only thing I'm finding is uses of the onload function and jQuery tricks for the same.  So I made my own flag... see new PR.

**Comment by jourdain** [comment]
I'll search for you on google for the proper flag name so you won't have to create something that already exist.

**Comment by jourdain** [comment]
Here it is: http://www.w3schools.com/jsref/prop_img_complete.asp

**Comment by mathturtle** [comment]
I missed that.  But I don't think it will do what we want since we don't set the src on the image until the imageProvider fires...

>HTMLImageElement.complete 
>Returns a Boolean that is true if the browser has finished fetching the image, whether successful or not. It also shows true, if the image has no src value.

From: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement

**Comment by jourdain** [comment]
That's why " if (image.src && image.complete)"

**Pull request merged**
