### PR TITLE
Histogram style fix

### PR DESCRIPTION
**Pull request by aronhelser**
@scottwittenburg @jourdain @patrickoleary After the kids go to bed...
Here's the style and functionality fixes that we went over last week. I think I've hit all the style fixes, but I still have to enforce that the uncertainty regions can't overlap. Let me know if you recall anything I missed.

### CODE REVIEW

**Comment by scottwittenburg** [comment]
This is looking great, @aronhelser, thanks!  Seems like you hit all the points we discussed a couple weeks ago.  I love the ability to choose the number of histograms per row.  I just have a couple thoughts/questions:

1) What does it mean to score a parameter which is not selected?  Perhaps the "selectedness" is just something we can choose to take advantage of in applications, but scoring and selection are truly separate things that should have no relationship to each other.

2) Do you think the selection border stands out enough from the non-selected border?  My first thought was that it should be thicker, but perhaps not.

LGTM.  I'd be fine having this merged.

**Comment by scottwittenburg** [comment]
Except now you may have to rebase again, because I just merged my topic.  Sorry.

**Comment by scottwittenburg** [comment]
And while you're at it, perhaps change the height and line height on the histogram selector header to 25px?  We like how it gives a bit more space.  What do you think?

**Comment by aronhelser** [comment]
OK, I can update the line height. I had it approximately matching the field selector. 

Should I make a note to update the field selector?

**Comment by aronhelser** [comment]
You can't use 'selected' that way anymore :earth_americas: In the code, those are 'active', and I thought about making the field active if you scored it, but that would automatically add the field to parallel coords and MI. Do we actually want that?

I think the styling for active/inactive is good, because the individual headers/glyphs grey out as well, so I find it pretty clear. I'm happy to tweak, though - send me some numbers, if you like!

**Comment by scottwittenburg** [comment]
My personal feeling is don't worry about the field selector.  I'm happy with everything else as well, so feel free to merge once the button goes green.

**Comment by aronhelser** [comment]
I like the 25 px height for the header, too. I added a 'crisp-edges' for the hist rects, too. 

Next meeting, we should chat about 'active' and what it means for objective functions...

**Pull request merged**
